[[credentials_and_proxies]]
username = 'user1'
password = 'pass1'
proxies = ['proxy1:port1', 'proxy2:port2']

[[credentials_and_proxies]]
username = 'user2'
password = 'pass2'
proxies = ['proxy3:port3', 'proxy4:port4']
